baseURL = 'http://francesco.1hcremona.cf/'
languageCode = 'en-us'
title = 'Portfolio'
theme = 'hugo-theme-shell'

[Params]
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "Francesco Silvani's Portfolio!"
  [Params.Terminal]
  # Note: color schema
  # Note: You can choose between
  # Note: ["monokai", "powershell", "gruvbox_light", "gruvbox_dark", "solarized_light", "solarized_dark", "ubuntu", "retro"]
  # Note: If you want to use the Goph theme, set it to "goph" (See README.md)
  schema = "solarized_dark"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "francesco"
  pcName = "laptop"
  workDir = "life"
  profile = "profile.conf"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: If you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  terminalDelay = 50

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: If you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  activityDelay = 5

  description = """
  Hi I am Francesco Silvani!
  I am a 13 year old programmer and tech enthusiast.
  I am currently working on this site.

  """

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "abilities"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["C/C++", "/languages/C++.md"],
    ["C#", "/languages/Csharp.md"],
    ["Python", "/languages/Python.md"],
    ["JavaScript", "/languages/Javascript.md"],
    ["Linux", "/languages/Linux.md"],
  ]
